// Independent fixtures are generated by scripts/validate_rsaref_scanner.py.
// Include the production translation unit so its internal functions are tested
// without changing scanner behavior or adding a test-only production interface.
#define main rsaref_scanner_production_main
#include "../src/rsaref_md5_state_scan.cpp"
#undef main

#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>

namespace controls {

std::vector<std::string> Fields(const std::string& line) {
  std::vector<std::string> fields;
  std::size_t first = 0;
  for (;;) {
    const auto last = line.find('\t', first);
    fields.push_back(line.substr(first, last - first));
    if (last == std::string::npos) return fields;
    first = last + 1;
  }
}

std::vector<unsigned char> Bytes(const std::string& hex) {
  if (hex.size() % 2) throw std::runtime_error("odd hexadecimal length");
  std::vector<unsigned char> bytes;
  for (std::size_t i = 0; i < hex.size(); i += 2)
    bytes.push_back(static_cast<unsigned char>(
        std::stoul(hex.substr(i, 2), nullptr, 16)));
  return bytes;
}

Block FixedBlock(const std::string& hex) {
  const auto bytes = Bytes(hex);
  if (bytes.size() != 16) throw std::runtime_error("wrong block length");
  Block result{};
  std::copy(bytes.begin(), bytes.end(), result.begin());
  return result;
}

Transition Counter(const std::string& name) {
  if (name == "post") return Transition::kPostincrement;
  if (name == "pre") return Transition::kPreincrement;
  throw std::runtime_error("unknown transition");
}

struct PlantedControl {
  std::string id;
  std::string mode;
  std::uint32_t candidate;
  unsigned word_bytes;
  Transition transition;
  unsigned selected_width;
  Block state;
  TargetModel model;
  mpz_class expected_p;
  mpz_class expected_q;
};

void Require(bool condition, const std::string& message) {
  if (!condition) throw std::runtime_error(message);
}

WidthModel& Width(std::vector<WidthModel>& widths, unsigned bits) {
  for (auto& width : widths)
    if (width.digit_bits == bits) return width;
  throw std::runtime_error("missing width model");
}

int Run(const char* path) {
  std::ifstream file(path);
  Require(file.good(), "cannot open fixture file");
  std::map<std::string, PlantedControl> planted;
  std::map<std::string, unsigned> counts;
  TargetModel real = Rsa270Model();
  std::string line;
  unsigned line_number = 0;
  while (std::getline(file, line)) {
    ++line_number;
    if (line.empty() || line.front() == '#') continue;
    const auto f = Fields(line);
    const auto& type = f.at(0);
    const std::string label = type + " fixture line " + std::to_string(line_number);
    if (type == "TARGET") {
      Require(real.target == mpz_class(f.at(1), 10), label);
    } else if (type == "INITSET") {
      const auto actual = InitialStates(f.at(1), std::stoul(f.at(2)),
                                        std::stoul(f.at(3)));
      Require(actual.size() == std::stoul(f.at(4)), label);
    } else if (type == "INIT") {
      const auto actual = InitialStates(f.at(1), std::stoul(f.at(2)),
                                        std::stoul(f.at(3)));
      unsigned matches = 0;
      for (const auto& named : actual)
        if (named.first == f.at(4)) {
          ++matches;
          Require(named.second == FixedBlock(f.at(5)), label);
        }
      Require(matches == 1, label + " unique family name");
    } else if (type == "STEP") {
      auto state = FixedBlock(f.at(2));
      for (unsigned i = 0; i < std::stoul(f.at(3)); ++i)
        Step(&state, Counter(f.at(1)));
      Require(state == FixedBlock(f.at(4)), label);
    } else if (type == "STREAM") {
      Require(Stream(FixedBlock(f.at(2)), Counter(f.at(1)),
                     std::stoul(f.at(3))) == Bytes(f.at(4)), label);
    } else if (type == "ACCEPT") {
      Require(Accepted(mpz_class(f.at(1), 10)) == (f.at(2) == "1"), label);
    } else if (type == "PRIME") {
      Require(FindPrime(mpz_class(f.at(1), 10), std::stoul(f.at(2))) ==
                  mpz_class(f.at(3), 10), label);
    } else if (type == "REAL_WIDTH") {
      const auto& width = Width(real.widths, std::stoul(f.at(1)));
      Require(width.target_offset == std::stoul(f.at(2)) &&
                  width.target_block_bytes == std::stoul(f.at(3)) &&
                  width.anchors.size() == std::stoul(f.at(4)), label);
    } else if (type == "REAL_ANCHOR") {
      const auto& width = Width(real.widths, std::stoul(f.at(1)));
      unsigned matches = 0;
      for (const auto& anchor : width.anchors)
        if (anchor.index == std::stoul(f.at(2))) {
          ++matches;
          Require(anchor.digest == FixedBlock(f.at(3)), label);
        }
      Require(matches == 1, label + " unique anchor index");
    } else if (type == "CONTROL") {
      PlantedControl control{};
      control.id = f.at(1);
      control.mode = f.at(2);
      control.candidate = std::stoul(f.at(3));
      control.word_bytes = std::stoul(f.at(4));
      control.transition = Counter(f.at(5));
      control.selected_width = std::stoul(f.at(6));
      control.state = FixedBlock(f.at(7));
      control.model.p_bits = std::stoul(f.at(8));
      control.model.q_bits = std::stoul(f.at(9));
      control.model.target = mpz_class(f.at(10), 10);
      control.expected_p = mpz_class(f.at(11), 10);
      control.expected_q = mpz_class(f.at(12), 10);
      Require(planted.emplace(control.id, std::move(control)).second, label);
    } else if (type == "CONTROL_WIDTH") {
      planted.at(f.at(1)).model.widths.push_back(
          {static_cast<unsigned>(std::stoul(f.at(2))),
           std::stoul(f.at(3)), std::stoul(f.at(4)), {}});
    } else if (type == "CONTROL_ANCHOR") {
      Width(planted.at(f.at(1)).model.widths, std::stoul(f.at(2))).anchors.push_back(
          {static_cast<unsigned>(std::stoul(f.at(3))), FixedBlock(f.at(4))});
    } else {
      throw std::runtime_error("unknown fixture record: " + type);
    }
    ++counts[type];
  }

  unsigned product_controls = 0, state_controls = 0, miss_controls = 0;
  for (const auto& [id, control] : planted) {
    std::printf("independent-control id=%s width=%u transition=%s\n",
                id.c_str(), control.selected_width,
                control.transition == Transition::kPostincrement ? "post" : "pre");
    unsigned selected = 0;
    Require(Probe(control.state, control.transition, control.model.widths,
                  &selected) && selected == control.selected_width,
            id + " must select intended width");
    for (const auto& width : control.model.widths) {
      const bool expected = width.digit_bits == control.selected_width;
      Require(Verify(control.state, control.transition, width) == expected,
              id + " selected width is the only accepting model");
      if (expected) {
        const auto actual = ModeledPrimes(
            Stream(control.state, control.transition,
                   width.target_offset + 2 * width.target_block_bytes),
            width, control.model);
        Require(actual.first == control.expected_p &&
                    actual.second == control.expected_q,
                id + " independent ordered factors");
      }
    }
    const std::uint64_t seed = control.candidate;
    Require(RunScan(control.mode, seed - 3, seed + 3, 2,
                    control.word_bytes, control.model) == Outcome::kProductMatch,
            id + " expected product match");
    ++product_controls;
    auto mismatched = control.model;
    mismatched.target += 1;
    Require(RunScan(control.mode, seed - 3, seed + 3, 2,
                    control.word_bytes, mismatched) == Outcome::kStateOnly,
            id + " expected state-only result for wrong target");
    ++state_controls;
    Require(RunScan(control.mode, seed + 1000, seed + 1006, 2,
                    control.word_bytes, control.model) == Outcome::kNone,
            id + " expected no match outside planted range");
    ++miss_controls;
  }
  for (const auto& [type, count] : counts)
    std::printf("fixtures type=%s checked=%u\n", type.c_str(), count);
  Require(counts["REAL_ANCHOR"] == 63, "all 63 real anchors must be checked");
  Require(counts["INITSET"] == 87, "all initial-state fixture groups must be checked");
  Require(product_controls == 6 && state_controls == 6 && miss_controls == 6,
          "all width/transition outcomes must be checked");
  std::printf("independent-validation PASSED product_controls=%u "
              "state_only_controls=%u no_match_controls=%u threads=2\n",
              product_controls, state_controls, miss_controls);
  return 0;
}

}  // namespace controls

int main(int argc, char** argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: %s FIXTURES.tsv\n", argv[0]);
    return 2;
  }
  try {
    return controls::Run(argv[1]);
  } catch (const std::exception& error) {
    std::fprintf(stderr, "independent-validation FAILED: %s\n", error.what());
    return 1;
  }
}
